name: new pr

on:
  pull_request:
    types: [opened, labeled]

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack pr open
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
          PULL_REQUEST_AUTHOR_NAME: ${{ github.event.pull_request.user.login }}
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
          PULL_REQUEST_BODY: ${{ github.event.pull_request.body }}
        uses: jun3453/slack-pr-open-notification-action@v1.3.0
